first = complex(input('Enter first complex number: '))
print(first.real)
print(first.imag)
second = complex(input('Enter first complex number: '))
print(second.real)
print(second.imag)
sum = first + second
print(sum)
print(sum.real)
print(sum.imag)